Test: Fix incorrect namespace package: nspkg3_bbb
The nspkg3 namespace package contains the zipped egg: `nspkg3_bbb.egg`.
This package contains a `namespace_packages.txt` file incorrectly
listing two namespaces: `nspkg3` and `nspkg3.bbb`. The second entry is
not a valid namespace package as it is a package within the `nspkg3`
namespace`. This causes an obscure error: when attempting to import any
packages under `nspkg3.bbb` while having any other egg in the
`nspkg3-pkg` directory on `PYTHONPATH`, an `ImportError` will be raised.
The only way the import can work is if the only egg on the `PYTHONPATH`
is the invalid egg itself.

This breaks the `test_nspkg3_bbb_zzz` test when using
`--use-default-hook` as the `collect_all` call will attempt to import
the bad namespace package.

The fix is fairly simple: we just need to remove the extra entry from
`namespace_packages.txt`. I made this change and zipped up the egg
again.

Before:
```
$ cat EGG-INFO/namespace_packages.txt
nspkg3
nspkg3.bbb
$ PYTHONPATH=nspkg3_aaa.egg:nspkg3_bbb.egg python3.7 -c "import nspkg3.bbb"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nspkg3.bbb'
$ PYTHONPATH=nspkg3_bbb.egg python3.7 -c "import nspkg3.bbb"
$
```

After:
```
$ cat EGG-INFO/namespace_packages.txt
nspkg3
$ PYTHONPATH=nspkg3_aaa.egg:nspkg3_bbb.egg python3.7 -c "import nspkg3.bbb"
$
```