Compat: Fix `unexpected keyword argument` error in exec_command_all().
Fix
TypeError: __init__() got an unexpected keyword argument 'encoding'
when subprocess.Popen() is called.

This showed up with the test I just added. Obviously exec_command_all()
was never called with an `encoding` passed.