compat: add support for Python 3.10
Add is_py310 variable. Include _bootlocale module in PY3_BASE_MODULES
only for Python versions earlier than 3.10.

bootloader & archive: switch pyvers value to 100*major + minor

Under the formerly used schema (10*major + minor), the value for
python 3.10 collides with potential python 4.0.

The value being 40 for python 3.10 would also break the AIX-specific
codepath pyi_pylib_load() that tries to decomponse the value back
into major and minor versions. It would also break the Windows-only
pyi_pylib_attach() function (which appears to be unused, however).

depend/bytecode: add support for CALL_FUNCTION_EX with const args

In python 3.10, if a function is called with more than 30 const
arguments, CALL_FUNCTION_EX is used with a single tuple containing
all values.

Fixes failing part of test_global_functions with many_arguments
under python 3.10.

tests: disable unavailable package requirements

Disable package requirements that are currently unavailable for
python 3.10 (wheels not yet available, and fail to build from
sdist).

tests: annotate test_path_encodings.py tests that depend on win32api

Add @importorskip('win32api') to test_win_py3_no_shortpathname and
test_win_TEMP_has_shortpathname from test_path_encodings.py that
depend on win32api.

tests: remove test_option_runtime_tmpdir dependency on win32api

When the test was introduced in e745d95e0c961a1eb4a4ba52b7320bd3d8fd66ef,
it had a special codepath for python 2 on Windows that used win32api.
That codepath had been removed since then, but the import remained.

tests: skip TestModuleGraph::test_create_xref if lxml is unavailable

It is the only test in our whole test suite that makes use of the
lxml, so this allows us to run the remaining test suite even if
lxml is unavailable.

tests: disable numpy on macOS and python 3.10

Compiling from sdist seems to produce numpy that fails to pass
its sanity check:

```
RuntimeError: Polyfit sanity test emitted a warning, most likely
due to using a buggy Accelerate backend. If you compiled yourself,
more information is available at
https://numpy.org/doc/stable/user/building.html#accelerated-blas-lapack-libraries
Otherwise report this to the vendor that provided NumPy.
```