hooks: tkinter: collect Tcl modules directory
The Tcl modules directory is separate from the data/library one,
and is typically located at `tcl_root/../tclX`, where `tcl_root`
is the Tcl data/library directory and `X` is the Tcl major version.

In most (simple?) cases, failing to collect this directory does
not seem to cause any issues. One notable exception are .app
bundles on OSX, which "open and close immediately" due to the
following exception, caused by the missing msgcat module:
```
_tkinter.TclError: invalid command name "msgcat::mc"
```