building: utils: switch bincache hashes from md5 to sha1
On FIPS-enabled RHEL systems, `hashlib.md5()` raises exception:
```
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled
for FIPS
```

So switch to SHA1 instead.