building: BUNDLE: use xattr package for extended attribute check
Instead of using system-provided `/usr/bin/xattr` utility to list
the extended attributes on collected files, add an optional
dependency on `xattr` package and use `xattr.listxattr` function.

Turns out that system-provided `/usr/bin/xattr` is in fact just an
entry-point provided by the `xattr` package installed in the
system-provided python, which on macOS <= 11 is still python2.
Therefore, trying to run it in a sub-process from python3 might
lead to weird compatibility issues to due python3 site-packages
leaking into the python2 process, as seen on our CI:

```
 output: Traceback (most recent call last):
  File "/usr/bin/xattr", line 8, in <module>
    from pkg_resources import load_entry_point
  File "/Users/runner/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1423
    local = f"sanitized.{_safe_segment(rest)}".strip(".")
                                              ^
SyntaxError: invalid syntax
```