Hooks: Add hidden import from a Python 2.7 failure::
Traceback (most recent call last):
  File "c:\users\appveyor\appdata\local\temp\1\pytest-of-appveyor\pytest-1\popen-gw0\test_lxml_isoschematron_onefil0\test_lxml_isoschematron.py", line 5, in <module>
    from lxml import isoschematron
  File "C:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "c:\python27\lib\site-packages\lxml\isoschematron\__init__.py", line 7, in <module>
    from lxml import etree as _etree # due to validator __init__ signature
  File "C:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 678, in load_module
    module = imp.load_module(fullname, fp, filename, ext_tuple)
  File "src\lxml\serializer.pxi", line 625, in init lxml.etree
ImportError: No module named contextlib