Fix: Runtests crashes when option `--interactive-tests` is used.
The error was:
TypeError: __init__() got an unexpected keyword argument 'with_crypto'