Fix #1149: AttributeError: 'module' object has no attribute 'rstrip'.
First, `rstrip` is a method of string/unicode-strings anyway.
Second, using it was useless anyway, since os.path.join takes care of it.