bootloader: specify missing header for _NSGetExecutablePath
On using a custom build of Clang, build on macOS fails with:
../../src/pyi_main.c:997:9: error: call to undeclared function '_NSGetExecutablePath';
    if (_NSGetExecutablePath(program_path, &name_length) != 0) {
        ^
1 error generated.

The missing header was lost in the refactor at:
https://github.com/pyinstaller/pyinstaller/commit/c3167147