Fix bootloader compilation
Error message:

../common/main.c: In function 'stb_decompress_fromfile':
../common/stb.h:10105:9: error: ignoring return value of 'fread',
declared with attribute

warn_unused_result [-Werror=unused-result]
../common/main.c: In function 'stb_fget_string':
../common/stb.h:5718:9: error: ignoring return value of 'fread',
declared with attribute

warn_unused_result [-Werror=unused-result]
cc1: all warnings being treated as errors