Fix missing _MEIPASS attribute.
This is a fix for the following error:

Traceback (most recent call last):
  File "<string>", line 35, in <module>
  AttributeError: 'module' object has no attribute '_MEIPASS'

as discussed previously in http://www.pyinstaller.org/ticket/801

In this patch we fall back on os.path.dirname(sys.executable) when sys._MEIPASS
isn't present.