hooks: add aliyunsdkcore hook
oss2 is a package for Alibaba Cloud OSS, which is using aliyunsdkcore
package, which is using some data files inside. Currently, if you try to
build a package that is using oss2 with pyinstaller, you'll get this
error:

```
    import oss2
  File
"/home/efiop/.pyenv/versions/2.7.15/envs/2.7.15-dvc/src/pyinstaller/PyInstaller/loader/pyimod03_importers.py",
line 395, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/oss2/__init__.py", line 5, in <module>
  File
"/home/efiop/.pyenv/versions/2.7.15/envs/2.7.15-dvc/src/pyinstaller/PyInstaller/loader/pyimod03_importers.py",
line 395, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/oss2/api.py", line 177, in <module>
  File
"/home/efiop/.pyenv/versions/2.7.15/envs/2.7.15-dvc/src/pyinstaller/PyInstaller/loader/pyimod03_importers.py",
line 395, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/oss2/crypto.py", line 21, in <module>
  File
"/home/efiop/.pyenv/versions/2.7.15/envs/2.7.15-dvc/src/pyinstaller/PyInstaller/loader/pyimod03_importers.py",
line 395, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/aliyunsdkcore/client.py", line 44, in <module>
  File
"/home/efiop/.pyenv/versions/2.7.15/envs/2.7.15-dvc/src/pyinstaller/PyInstaller/loader/pyimod03_importers.py",
line 395, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/aliyunsdkcore/retry/retry_policy.py", line 33, in
<module>
  File "site-packages/aliyunsdkcore/retry/retry_condition.py", line 219,
in __init__
  File "site-packages/aliyunsdkcore/utils/__init__.py", line 23, in
_load_json_from_data_dir
IOError: [Errno 2] No such file or directory:
'/home/efiop/git/dvc/build/usr/lib/dvc/aliyunsdkcore/data/retry_config.json'
[19024] Failed to execute script __main__
```

which is caused by a missing `aliyunsdkcore/data/retry_config.json`.
This hook collects data files in aliyunsdkcore package.

Signed-off-by: Ruslan Kuprieiev <ruslan@iterative.ai>