tests: django: update the test django project
Re-generate the test django project using
`django-admin startproject django_site`
under Django 4.1.2. Fixes the `ImportError: cannot import name
'url' from 'django.conf.urls'` error due to `url` being deprecated
in Django 3.0 and removed in 4.0.

Also run the migrations to populate the database.